### PR TITLE
Fix Error in commentary on Prop 33

### PR DESCRIPTION
**Pull request by meygerjos**
Please check my math before accepting, but I am pretty sure I am right.

### CODE REVIEW

**Comment by mdnahas** [comment]
Thanks for submitting your finds!   I've already merged your other pull request.  

This pull request has found a problem, but I don't think your fix is correct.

You propose:
   a=false, b=false, c=true, d=false
which yields
   [(false->false)/\(true->false)]->[(false\/true)->(false\/false)]
  = [true /\ false] -> [ true -> false ]
  = false -> false
  = true

I did a truth table with all 16 values for a,b,c, and d.  They all worked.  It looks like proposition 33 holds. 
I also did a truth table for the commentary's suggested change to proposition 33.  It fails for a=true, b=c=d=false.
I think the correct fix is just to delete the commentary.  

Do you agree?

**Comment by meygerjos** [comment]
The first operator is disjunction in Peano, right?

So then it would give

[(false->false)/(true->false)]->[(false/true)->(false/false)]
= [true / false] -> [ true -> false ]
= true -> false
= false

Thanks for translating this!

**Comment by mdnahas** [comment]
No, it is conjunction ("and").   

The commentary suggests that it should be disjunction ("or"), but as your math shows, that would be wrong.  Thus, I think the best change is deleting the commentary.

**Comment by meygerjos** [comment]
Ah yes you're right.

**Comment by mdnahas** [comment]
I deleted the commentary on 33.

Closed with commit cbb8cb47116ad16654d08b13748ec8417d2ac7db

**Pull request closed without merging**
